##Application.Yml configFile

#Tomcat config
server:
  port: 8080
  servlet:
    context-path: /crm

spring:
  # datasource/database config
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/crm?userUnicode=true&characterEncoding=utf8&serverTimeZone=GMT%2B8
    username: root
    password: root
  #freeemarker
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: utf-8
    template-loader-path: classpath:/views/
  #DevTools
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
#MyBatis config
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.baldprogrammer.crm.vo;com.baldprogrammer.crm.query;com.baldprogrammer.crm.dto
  configuration:
    map-underscore-to-camel-case: true
#pagehelper config
pagehelper:
  helper-dialect: mysql

# set dao log output
logging:
  level:
    com:
      baldprogrammer:
                 crm: debug